export type Verdict = 'verified' | 'misleading' | 'false' | 'insufficient_evidence';

export interface Evidence {
  title: string;
  url: string;
  publisher: string;
  rating?: string;
}

export interface FactCheckResult {
  verdict: Verdict;
  explanation: string;
  evidence: Evidence[];
  /** 'certified' = a published fact-checker reviewed this claim.
   *  'ai_assessment' = generated by a model over retrieved snippets. */
  basis: 'certified' | 'ai_assessment' | 'none';
}
